// flow-typed signature: f040ee5cfd6e7e53e0bc423e857ea712
// flow-typed version: <<STUB>>/react-native-chooser_v^1.7.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-chooser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-chooser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-chooser/lib/indicator' {
  declare module.exports: any;
}

declare module 'react-native-chooser/lib/option' {
  declare module.exports: any;
}

declare module 'react-native-chooser/lib/optionlist' {
  declare module.exports: any;
}

declare module 'react-native-chooser/lib/select' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-chooser/index' {
  declare module.exports: $Exports<'react-native-chooser'>;
}
declare module 'react-native-chooser/index.js' {
  declare module.exports: $Exports<'react-native-chooser'>;
}
declare module 'react-native-chooser/lib/indicator.js' {
  declare module.exports: $Exports<'react-native-chooser/lib/indicator'>;
}
declare module 'react-native-chooser/lib/option.js' {
  declare module.exports: $Exports<'react-native-chooser/lib/option'>;
}
declare module 'react-native-chooser/lib/optionlist.js' {
  declare module.exports: $Exports<'react-native-chooser/lib/optionlist'>;
}
declare module 'react-native-chooser/lib/select.js' {
  declare module.exports: $Exports<'react-native-chooser/lib/select'>;
}
